# Generated by Django 3.2.8 on 2021-10-08 11:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('pipeline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('context', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('Pipeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatransform.pipeline')),
            ],
        ),
    ]
