# Generated by Django 3.2.8 on 2022-11-14 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('pipeline_id', models.AutoField(primary_key=True, serialize=False)),
                ('pipeline_name', models.CharField(default='', max_length=100)),
                ('output_id', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=50)),
                ('dataset_id', models.CharField(max_length=50)),
                ('resource_identifier', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('context', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('order_no', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('result_url', models.CharField(max_length=500)),
                ('output_id', models.CharField(default='', max_length=200)),
                ('Pipeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatransform.pipeline')),
            ],
        ),
    ]
