# Generated by Django 3.2.8 on 2022-11-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatransform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='resource_identifier',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
