# Generated by Django 3.2.8 on 2022-11-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatransform', '0002_alter_pipeline_resource_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='db_action',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
