# Generated by Django 3.2.8 on 2021-10-09 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatransform', '0003_pipeline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='task',
            name='result_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
