# Generated by Django 3.2.8 on 2022-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatransform', '0003_pipeline_db_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='err_msg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='resultant_res_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
