# Generated by Django 3.2.8 on 2022-01-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatransform', '0004_auto_20211009_0843'),
        ('datatransform', '0004_auto_20211010_1933'),
    ]

    operations = [
    ]
